### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by sjm1992st** [StevenBirdBrown/weibo-emoji-predict#1]
i want to do same things, so could you share your data to me, thank u

**Comment by StevenBirdBrown** [comment]
You can download data from [this link](https://drive.google.com/open?id=1X0mVoaTxTugL7dxYlZh-B5AqnwfWB2Cf). I guess they are crawled from weibo (maybe another class project, lol) and arranged in chronological order, i.e., from the beginning of 2018 to perhaps the end of it.
